### ISSUE TITLE
ULN2003 driver 

### ISSUE THREAD

**Issue by Alfarouq21** [euphy/polargraph_server_a1#5]
how to fix this errors:

Arduino: 1.6.13 (Windows 10), Board: "Arduino/Genuino Uno"

configuration:99: error: 'Step' does not name a type

 Step angle (8-step) 5.625deg, 64 steps per rev;

 ^

configuration:100: error: 'Step' does not name a type

 Step angle (4-step) 11.25deg, 32 steps per rev;

 ^

configuration:101: error: 'gear' does not name a type

 gear reduction ratio 1/63.68395;

 ^

configuration:103: error: 'motorStepsPerRev' does not name a type

  motorStepsPerRev = 32 * 63.68395 = 2038; //for 4 step sequence

  ^

configuration:104: error: 'motorStepsPerRev' does not name a type

  motorStepsPerRev = 64 * 63.68395 = 4076; //for 8 step sequence

  ^

configuration:106: error: 'motorStepsPerRev' does not name a type

 motorStepsPerRev = 4076;

 ^

configuration:107: error: 'mmPerRev' does not name a type

  mmPerRev = 63;

  ^

configuration:108: error: 'intDEFAULT_STEPS_PER_REV' does not name a type

   intDEFAULT_STEPS_PER_REV = 4076;

   ^

configuration:109: error: 'intDEFAULT_MM_PER_REV' does not name a type

  intDEFAULT_MM_PER_REV = 63;

  ^

exit status 1
'Step' does not name a type

Invalid library found in C:\Program Files (x86)\Arduino\libraries\grbl-1.1e.20161219: C:\Program Files (x86)\Arduino\libraries\grbl-1.1e.20161219
Invalid library found in C:\Program Files (x86)\Arduino\libraries\grbl-master: C:\Program Files (x86)\Arduino\libraries\grbl-master
Invalid library found in C:\Program Files (x86)\Arduino\libraries\libraries: C:\Program Files (x86)\Arduino\libraries\libraries
Invalid library found in C:\Program Files (x86)\Arduino\libraries\mDrawBot-master: C:\Program Files (x86)\Arduino\libraries\mDrawBot-master
Invalid library found in C:\Program Files (x86)\Arduino\libraries\MotorParty: C:\Program Files (x86)\Arduino\libraries\MotorParty
Invalid library found in C:\Program Files (x86)\Arduino\libraries\MotorTest: C:\Program Files (x86)\Arduino\libraries\MotorTest
Invalid library found in C:\Program Files (x86)\Arduino\libraries\StepperTest: C:\Program Files (x86)\Arduino\libraries\StepperTest
Invalid library found in C:\Users\DR.Yahia\Documents\Arduino\libraries\shield: C:\Users\DR.Yahia\Documents\Arduino\libraries\shield
Invalid library found in C:\Program Files (x86)\Arduino\libraries\grbl-1.1e.20161219: C:\Program Files (x86)\Arduino\libraries\grbl-1.1e.20161219
Invalid library found in C:\Program Files (x86)\Arduino\libraries\grbl-master: C:\Program Files (x86)\Arduino\libraries\grbl-master
Invalid library found in C:\Program Files (x86)\Arduino\libraries\libraries: C:\Program Files (x86)\Arduino\libraries\libraries
Invalid library found in C:\Program Files (x86)\Arduino\libraries\mDrawBot-master: C:\Program Files (x86)\Arduino\libraries\mDrawBot-master
Invalid library found in C:\Program Files (x86)\Arduino\libraries\MotorParty: C:\Program Files (x86)\Arduino\libraries\MotorParty
Invalid library found in C:\Program Files (x86)\Arduino\libraries\MotorTest: C:\Program Files (x86)\Arduino\libraries\MotorTest
Invalid library found in C:\Program Files (x86)\Arduino\libraries\StepperTest: C:\Program Files (x86)\Arduino\libraries\StepperTest
Invalid library found in C:\Users\DR.Yahia\Documents\Arduino\libraries\shield: C:\Users\DR.Yahia\Documents\Arduino\libraries\shield

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by euphy** [comment]
Looks like you might have removed some comment marks ("//") from some of the documentation in configuration.ino. Revert all your changes and try again. Issues are for problems in the source code, rather than problems you've added yourself :)

Post a message on the forum (http://www.polargraph.co.uk/forum/) if you're looking for help with this. As I've mentioned, I have no direct experience of using this driver method.

**Comment by euphy** [comment]
Closing as "not an issue".
